spring:
    application.name: notification-service
    # rabbitmq:
    #     host: "rabbitmq"
    #     port: 5672
    #     username: "user"
    #     password: "password"
application:
    order-exchange: orders
    order-queue: orders.created.queue
    order-routing-key: orders.created
