name: e-commerce-platform
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:4.3.0-management
        environment:
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        ports:
            - 15672:15672 # UI
            - 5672:5672
    order-service:
        container_name: order-service
        build:
          context: ./order-service
          dockerfile: Dockerfile
        environment:
          SPRING_RABBITMQ_HOST: rabbitmq
          SPRING_RABBITMQ_PORT: 5672
          SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
          SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
          EXCHANGE_NAME: order.created
          QUEUE_NAME: queue
          ROUTING_KEY: order-queue
        ports:
          - 8081:8080
    inventory-service:
        container_name: inventory-service
        build:
          context: ./inventory-service
          dockerfile: Dockerfile
        ports:
          - 8082:8080
    notification-service:
        container_name: notification-service
        build:
          context: ./notification-service
          dockerfile: Dockerfile
        environment:
          SPRING_RABBITMQ_HOST: rabbitmq
          SPRING_RABBITMQ_PORT: 5672
          SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
          SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
          EXCHANGE_NAME: order.created
          QUEUE_NAME: queue
          ROUTING_KEY: order-queue
        ports:
          - 8083:8080
    analytics-service:
        container_name: analytics-service
        build:
          context: ./analytics-service
          dockerfile: Dockerfile
        ports:
          - 8084:8080