spring:
    application.name: order-service
    # rabbitmq:
    #     host: "rabbitmq"
    #     port: 5672
    #     username: "user"
    #     password: "password"
application:
    order-exchange: orders