spring:
    application.name: inventory-service
    # rabbitmq:
    #     host: "rabbitmq"
    #     port: 5672
    #     username: "user"
    #     password: "password"
application:
    order-exchange: orders
    order-queue: orders.queue
    order-routing-key: orders.*
    odoo:
        database: odoo
        host: ${APPLICATION_ODOO_HOST:odoo}
        port: ${APPLICATION_ODOO_PORT:8069}
        username: ${APPLICATION_ODOO_USERNAME:odoo@odoo.odoo}
        password: ${APPLICATION_ODOO_PASSWORD:odoo}