spring:
    application.name: inventory-service
    # rabbitmq:
    #     host: "rabbitmq"
    #     port: 5672
    #     username: "user"
    #     password: "password"
application:
    order-exchange: orders
    order-queue: orders.queue
    order-routing-key: orders.*